### ISSUE TITLE
Newgrounds background implementation

### ISSUE THREAD

**Issue by PersonMeetup** [PersonMeetup/personmeetup-web#5]
Instead of how I currently have my background set up, I feel an easier way to set it up would recreating [Newgrounds](https://www.newgrounds.com/)' backgrounds. For reference, here's how they're set up (with the current image replaced with Nunjucks of course.)

#### HTML

```html
<div class="skin-wrapper ">
  <div class="skin-inner">
    <div class="background" style="background-image: url('{{ngImage}}');">
      <img src="{{ngImage}}" alt="Newgrounds Background Image Theme"></div>
    <div class="skin-bars"></div>
  </div>
</div>
```

#### CSS

```css
body:not(.skin-userpage) div.outer div.skin-wrapper {
  position: absolute;
  top: 35px;
  width: 100%;
  height: calc(100% - 35px);
  left: 0px;
  pointer-events: none;
  z-index: -1;
  display: inline-block;
  overflow: hidden;
}

body:not(.skin-userpage) div.outer div.skin-inner {
  height: 100%;
  margin: 0px auto;
  max-width: 1520px;
  background-color: #22252A;
}

body:not(.skin-userpage) div.outer div.skin-inner div.background {
  width: 100%;
  position: relative;
  background-position: center;
  background-repeat: no-repeat;
}

body:not(.skin-userpage) div.outer div.skin-inner div.background img {
  vertical-align: middle;
  visibility: hidden;
}
```
